import { addBook, viewAllBooks, searchBooks, updateBook, deleteBook } from "./services/bookService.js"
import { borrowBook, returnBook } from "./services/borrowService.js"
import { addMember, viewAllMembers, searchMembers, updateMember, deleteMember } from "./services/memberService.js"
import { displayAnalytics, categoryInsights, yearFilter, unavailableBooks, activeBorrowMembers } from './services/reportService.js'

console.log("================== Adding Books ==================")
console.log(" ")
console.log(" ")
console.log("================== Viewing Books ==================")
console.log(" ")
console.log(" ")
console.log("================== Searching Books ==================")
console.log(" ")
console.log(" ")
console.log("================== Updating Books ==================")
console.log(" ")
console.log(" ")
console.log("================== Deleting Books ==================")
console.log(" ")
console.log(" ")
console.log("================== Adding Members ==================")
console.log(" ")
console.log(" ")
console.log("================== Viewing Members ==================")
console.log(" ")
console.log(" ")
console.log("================== Searching Members ==================")
console.log(" ")
console.log(" ")
console.log("================== Updating Members ==================")
console.log(" ")
console.log(" ")
console.log("================== Deleting Members ==================")
console.log(" ")
console.log(" ")
console.log("================== Borrowing Books ==================")
console.log(" ")
console.log(" ")
console.log("================== Returning Books ==================")
console.log(" ")
console.log(" ")
console.log("================== Library Analytics ==================")
console.log(" ")
console.log(" ")
console.log("================== Category Insights ==================")
console.log(" ")
console.log(" ")
console.log("================== Year Filter ==================")
console.log(" ")
console.log(" ")
console.log("================== Unavailable Books ==================")
console.log(" ")
console.log(" ")
console.log("================== Active Borrowers ==================")
console.log(" ")
console.log(" ")